from typing import Optional

DISABLE_DISCORD_VERSION_CHECKING: bool = False
DISABLE_BDAI_AUTOUPDATE: bool = False
USE_BD_CI_RELEASES: bool = False
GITHUB_TOKEN: Optional[str] = None
WORKFLOW_RUNS_LIMIT: int = 5

DISCORD_PARENT_PATH: Optional[str] = None
DISCORD_CANARY_PARENT_PATH: Optional[str] = None
DISCORD_PTB_PARENT_PATH: Optional[str] = None
LAST_INSTALLED_DISCORD_VERSION: Optional[str] = None
LAST_INSTALLED_DISCORD_CANARY_VERSION: Optional[str] = None
LAST_INSTALLED_DISCORD_PTB_VERSION: Optional[str] = None

LAST_INSTALLED_BD_VERSION: Optional[str] = None
LAST_INSTALLED_BD_CI_VERSION: Optional[str] = None
